services:

  seq:
    image: datalust/seq:latest
    env_file: development.env
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data

  redis: 
    image: redis:8-alpine
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rabbitmq:
    image: rabbitmq:4-management
    env_file: development.env
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - TZ=Europe/Rome
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  animetakusan-main:
    image: animetakusan-main
    env_file: development.env
    build:
      context: .
      dockerfile: AnimeTakusan.API/Dockerfile
      target: final-debug
    ports:
      - 5016:8081
    environment:
      - ASPNETCORE_URLS=https://+:8081
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx      
      - TZ=Europe/Rome
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ~/.aspnet/https:/https:ro

  animetakusan-malsync:
    image: animetakusan-malsync
    env_file: development.env
    build:
      context: ../AnimeTakusan.MAL
      dockerfile: AnimeTakusan.MAL.API/Dockerfile
    ports:
      - 5175:5175
    environment:
      - ASPNETCORE_URLS=https://+:5175
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - TZ=Europe/Rome
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ~/.aspnet/https:/https:ro

volumes:
  seq-data: